theme: jekyll-theme-minimal
title: Luca Negrini
description: Luca Negrini's home site
logo: photo_small.jpg

mail-work: luca.negrini@corvallis.it
linkedin: https://www.linkedin.com/in/luca-negrini-4a9813160
scholar: https://scholar.google.com/citations?user=zGO9bhkAAAAJ&hl=en
research-gate: https://www.researchgate.net/profile/Luca_Negrini
orchid: https://orcid.org/0000-0001-9930-8854
researcherid: https://publons.com/researcher/3259949/luca-negrini/

