theme: jekyll-theme-minimal
title: Luca Negrini
description: Luca Negrini's home site

mail-work: luca.negrini@juliasoft.com
linkedin: https://www.linkedin.com/in/luca-negrini-4a9813160
scholar: https://scholar.google.com/citations?user=zGO9bhkAAAAJ&hl=en
research-gate: https://www.researchgate.net/profile/Luca_Negrini

